<h1>3.Hafta Ödev</h1>

In [2]:
# Soru 1 – Liste Metotları
# Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
# notlar = [85, 92, 76, 92, 100, 76, 85, 92]
# • Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
# • En yüksek ve en düşük notu bulun.
# • Notları küçükten büyüğe sıralayın.

In [8]:
points = [85, 92, 76, 92, 100, 76, 85, 92]
unique_list = list(set(points))
print(unique_list)
print("En yüksek not:",max(unique_list))
print("En düşük not:",min(unique_list))
print("Notlar(küçükten büyüğe):",list(sorted(unique_list)))

[100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Notlar(küçükten büyüğe): [76, 85, 92, 100]


In [ ]:
# Soru 2 – Sayılar
# Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.
# Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
# Örn: 153 → 1³+5³+3³ = 153

In [30]:
def isArmstrong(number_str):
    digits = [int(x) for x in number_str]
    total = sum([x**3 for x in digits])
    if total == int(number_str):
        print(f"{number_str} bir Armstrong sayıdır.")
        return True

str_number = input("Sayı giriniz: ")
isArmstrong(str_number)

Sayı giriniz:  153


153 bir Armstrong sayıdır.


True

In [32]:
# Soru 3 – Kümeler
# Aşağıdaki iki küme verilmiştir:
# A = {"Python", "R", "SQL", "Java"}
# B = {"C++", "Python", "JavaScript", "SQL"}
# • Ortak dilleri bulun.
# • Sadece A’da olan dilleri listeleyin.
# • İki kümenin birleşimini alfabetik olarak yazdırın.

In [38]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
A_and_B = A.intersection(B)
only_A = A.difference(B)
A_or_B = sorted(A.union(B))
print("Ortak dilleri bulun.",list(A_and_B))
print("Sadece A’da olan dilleri listeleyin.",list(only_A))
print("İki kümenin birleşimini alfabetik olarak yazdırın.",list(A_or_B))

Ortak dilleri bulun. ['Python', 'SQL']
Sadece A’da olan dilleri listeleyin. ['R', 'Java']
İki kümenin birleşimini alfabetik olarak yazdırın. ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [1]:
# Soru 4 – Modüller
# • random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
# • Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [5]:
import random
import statistics

number_list = random.sample(range(1, 101), 10)

print("Sayılar:", number_list)
print("Ortalama:", statistics.mean(number_list))
print("Standart sapma:", statistics.pstdev(number_list))

Sayılar: [16, 39, 88, 64, 81, 52, 28, 27, 48, 19]
Ortalama: 46.2
Standart sapma: 23.907321054438533


In [7]:
# Soru 5 – Fonksiyonlar
# kelime_sayacı(metin) adında bir fonksiyon yazın.
# Fonksiyon verilen metindeki:
# • toplam kelime sayısını
# • en uzun kelimeyi
# • en sık geçen kelimeyi döndürsün

In [15]:
def counter(text):
    words = text.split()
    word_count = len(words)
    longer_word = max(words,key=len)
    recursive = max(words,key=words.count)
    return word_count,longer_word,recursive

input_text = input("Metin giriniz")
word_count, longer_word, recursive = counter(input_text)
print(f"Toplam kelime sayısı: {word_count},En uzun kelime:{longer_word},En sık geçen kelime:{recursive}")

Metin giriniz ben çok ama çok iyiyim


Toplam kelime sayısı: 5,En uzun kelime:iyiyim,En sık geçen kelime:çok


In [27]:
# Soru 6 – Gömülü Fonksiyonlar
# Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
# sayilar = [5, 12, 7, 18, 24, 3, 16]
# • Sadece çift sayıları filtreleyin.
# • Bu sayıların karelerini bulun.
# • Karelerini azalan sırada sıralayın.


In [29]:
numbers = [5, 12, 7, 18, 24, 3, 16]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
sqrts = list(map(lambda x: x**2, even_numbers))
sorted_list = sorted(sqrts, reverse=True)

print("Çift sayılar:", even_numbers)
print("Kareleri:", sqrts)
print("Sıralı hali:", sorted_list)

Çift sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Sıralı hali: [576, 324, 256, 144]


In [31]:
# Soru 7 – Lambda İfadeleri
# Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
# kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
# Bunu sorted + lambda ile yapın.

In [41]:
words = ["veri", "bilim", "analiz", "yapayzeka", "python"]
sorted_list = sorted(words, key=lambda x: len(x))
print(sorted_list)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [9]:
# Soru 8 – Metodlar
# Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
# yazın.
# Örn: "abc12def3" → 12 + 3 = 15


In [11]:
def number_sum(str):
    sum=0
    number =""
    
    for s in str:
        if s.isdigit():
            number += s
        else:
            if number:
                sum += int(number)
                number = ""
    if number:
        sum += int(number)

    return sum

my_text = input("Metin giriniz:")
print("Metin içinde geçen rakamların toplamı:",number_sum(my_text))

Metin giriniz: abc12def3


Metin içinde geçen rakamların toplamı: 15


In [15]:
import re

def number_sum(str):
    numbers = re.findall(r'\d+', str)  # \d sadece [1,2,3] - \d+ [123]
    return sum(int(number) for number in numbers)

my_text = input("Metin giriniz:")
print("Metin içinde geçen rakamların toplamı:",number_sum(my_text))

Metin giriniz: abc12def3


Metin içinde geçen rakamların toplamı: 15


In [17]:
#  9 – (Ekstra) Numpy 1
# 10 elemanlı bir numpy dizisi oluşturun.
# • Elemanlar 0–50 arasında rastgele sayılar olsun.
# • Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.

In [31]:
import numpy as np

my_array = np.random.randint(0,50,10)
average = np.mean(my_array)
std = np.std(my_array)
max_value = np.max(my_array)
print(my_array)
print(f"Ortalama:{average},standart sapma:{std},en büyük değer:{max_value}")

[32 16 23 35  7 46 19  0 15 33]
Ortalama:22.6,standart sapma:13.290598180668917,en büyük değer:46


In [33]:
# Soru 10 – (Ekstra) Numpy 2
# 5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
# • Her sütunun ortalamasını bulun.
# • 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [65]:
import numpy as np

my_array = np.random.random_sample((5,5))
print("Matris")
print(my_array)
col_means = my_array.mean(axis=1)  
binary_matrix = (my_array > 0.5).astype(int)

print("Binary matrisi:")
print(binary_matrix)
print("Ortalamalar:",col_means)

Matris
[[0.53536494 0.80230261 0.15473695 0.17120279 0.87104512]
 [0.89093052 0.58498248 0.48776245 0.33784254 0.29188185]
 [0.57047663 0.65084811 0.00964222 0.41400646 0.78954263]
 [0.5660586  0.66050348 0.14414152 0.83562585 0.13554082]
 [0.11488869 0.7075113  0.37989009 0.71261527 0.44074982]]
Binary matrisi:
[[1 1 0 0 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 1 0]
 [0 1 0 1 0]]
Ortalamalar: [0.50693048 0.51867997 0.48690321 0.46837405 0.47113104]
